### ISSUE TITLE
Invalid Mesh input error

### ISSUE THREAD

**Issue by sonumathur** [fwilliams/point-cloud-utils#24] opened 2020-10-13 06:10 UTC
what is reason for value error in python3.6 as
valueError: Invalid input mesh with zero elements: v and f must have shape (n, 3) and (m, 3) (n, m > 0). Got v.shape =(119844, 3), f.shape = (0, 0).

The PLY is opening good in other programs.

**Comment by fwilliams** [comment] 2020-10-14 14:54
Hi @sonumathur thanks for posting! 

Is this is an error with `read_ply`? I've had no trouble opening PLYs with no faces, but maybe there's something different with yours that's making the code hit a bug. Could you send me a PLY file to reproduce your bug and I'll look into it?

**Comment by sonumathur** [comment] 2020-10-14 15:09
Ply Files

**Comment by fwilliams** [comment] 2020-10-14 16:29
I ran into no issues loading these PLY files:

![image](https://user-images.githubusercontent.com/1343232/96018128-df1a9f80-0e18-11eb-966e-e9658bbacda1.png)


What version of Point Cloud Utils are you using? What operating system are you using? Did you install from conda?

**Comment by sonumathur** [comment] 2020-10-15 04:09
I have installed conda. I tried example you have provided at start page as :-1: 
import point_cloud_utils as pcu
# v is a nv by 3 NumPy array of vertices
# f is an nf by 3 NumPy array of face indexes into v 
# n is a nv by 3 NumPy array of vertex normals
v, f, n, _ = pcu.read_ply("my_model.ply")

# Generate 10000 samples on a mesh with poisson disk samples
v_poisson, n_poisson = pcu.sample_mesh_poisson_disk(
    v, f, n, 10000, use_geodesic_distance=True)

I am new to point cloud 
I try this example as
![12](https://user-images.githubusercontent.com/60248559/96076121-33ca2300-0eca-11eb-85af-819ea96acfd8.jpg)

There is some error.

**Comment by fwilliams** [comment] 2020-10-15 17:46
This error is because your loaded mesh is a point cloud not a mesh with faces. The function `sample_mesh_poisson_disk` expects a triangle mesh on which to generate new samples. 

If you only have a dense point cloud, you can dowsample it to have the poisson disk property using `prune_point_cloud_poisson_disk`. This function will discard points in your pointcloud so that it has the poisson disk property. 

Note: You should upgrade to version 0.16.0 (which was released today on Mac and Linux) since I made some updates to `prune_point_cloud_poisson_disk`.

**Comment by fwilliams** [comment] 2021-04-07 14:18
I think this question is answered so I'm closing the issue. Here is the relevant documentation link:

[Documentation for downsampling a point cloud to have a blue noise distribution](https://github.com/fwilliams/point-cloud-utils#downsample-a-point-cloud-to-have-a-blue-noise-distribution)

**Closed by fwilliams** 2021-04-07 14:18 UTC
