### ISSUE TITLE
Succesful install, but functions not working properly

### ISSUE THREAD

**Issue by tverbrug** [fwilliams/point-cloud-utils#7] opened 2019-09-04 09:26 UTC
Hello,

I was able to succesfully install your library using the pip method on Ubuntu 18.04. I am able to import the module into python and I can run the test_examples.py script. However, when I look at the results, I see that the sampling functions do not work. Both pcu.sample_mesh_random() and pcu.sample_mesh_poisson_disk() just result in the original vertices and faces. There are no error or warning messages.

![Screenshot from 2019-09-04 11-25-58](https://user-images.githubusercontent.com/17294070/64242983-d31a9980-cf06-11e9-9011-c0f669e44096.png)

**Comment by fwilliams** [comment] 2019-09-27 23:52
Hey, thanks for reporting this!

The issue is that `sample_mesh_poisson_disk` downsamples a mesh using Poisson Disk sampling. Since you specify 100 times the number of vertices, you're going to get the whole mesh. If you have a mesh, you first need to upsample it. The new version of this library will include an `upsample_mesh` function which upsamples a mesh using subdivision.

**Comment by fwilliams** [comment] 2019-11-18 04:21
This is now fixed. `sample_mesh_poisson_disk` generates Poisson disk samples on the mesh. There's a new parameter to generate a given number of samples, or you can use the radius.

I also fixed the random mesh sampling function `sample_mesh_random` to properly upsample.

**Closed by fwilliams** 2019-11-18 04:21 UTC
