### ISSUE TITLE
Memory Leakage Issue and Request for Resolution

### ISSUE THREAD

**Issue by rathoddinesh14** [fwilliams/point-cloud-utils#63] opened 2023-05-04 07:28 UTC
Hi Francis,

I hope you are doing well. I wanted to contact you about a memory leakage issue while using your library. The memory is not being appropriately freed after each function call, especially when **iteratively** using the make_mesh_watertight function with large resolutions. Over time, this results in excessive memory consumption, eventually causing performance issues and potential crashes.

One specific instance where I noticed this issue was when executing the following code snippet:
```
for mesh in list_meshs:
    resolution = 20000
    vw, fw = pcu.make_mesh_watertight(mesh.vertices, mesh.faces, resolution=resolution)
```
Even after the completion of the make_mesh_watertight function, the memory usage remains high, and subsequent iterations lead to further memory consumption.

Please assist in investigating and addressing this memory leakage issue. Please prioritize this matter and provide a resolution to ensure the proper release of memory resources after each function call. This will significantly improve the efficiency and stability of the library.

If there are any additional details or steps I can provide to help resolve this issue, please do not hesitate to let me know. I am more than willing to collaborate and provide any necessary information.

Thank you.

**Comment by AppledoreM** [comment] 2023-06-10 12:00
I think the issue is in the external source used by this repository. I came across with the same issue today. This library use an external library named [manifold](https://github.com/hjwdzh/Manifold), and I believe there was some memory leaks in the code. You might need to compile point_cloud_utils from source after you edit those memory leak code out.

**Comment by fwilliams** [comment] 2023-06-29 20:18
Seems like a bug in Manifold yeah... If someone has a fix, I'll happily accept a PR!

**Comment by AppledoreM** [comment] 2023-06-30 04:58
I think I fixed the bug. I could create a fixed fork for Manifold repo this week, and maybe we could update the external folder dependency to use that fork in the PR.

**Comment by AppledoreM** [comment] 2023-07-07 03:59
I created a pr that fixes this several weeks ago, maybe we can try to merge it to main?

**Comment by fwilliams** [comment] 2023-07-07 16:55
Hey sorry @AppledoreM  I wanted to check the code chante in Manifold before merging. Can you link your branch here or in the PR? Then I'll merge it!

**Comment by AppledoreM** [comment] 2023-07-08 07:43
Sure, here is the link:
https://github.com/AppledoreM/Manifold

**Comment by fwilliams** [comment] 2023-07-09 02:35
Okay looks good!

**Comment by fwilliams** [comment] 2023-07-09 02:38
Okay it's merged! Can you try if it works?

**Comment by fwilliams** [comment] 2023-07-10 17:39
Okay I'm cutting a release of PCU! This should be fixed in the latest version. Big thanks @AppledoreM for your fix!

**Closed** 2023-07-10 17:40 UTC
